### ISSUE TITLE
Erro 500

### ISSUE THREAD

**Issue by miguelfep** [Apptha/Airhotels#3]
I'm getting 500 error when trying to move to next step experience register
log apache erro:  PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Varien_Object::addData() must be of the type array, null given, called in /var/www/html/magento/app/code/local/Apptha/Airhotels/controllers/GeneralController.php on line 54 and defined in /var/www/html/magento/lib/Varien/Object.php:243\nStack trace:\n#0 /var/www/html/magento/app/code/local/Apptha/Airhotels/controllers/GeneralController.php(54): Varien_Object->addData(NULL)\n#1 /var/www/html/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Apptha_Airhotels_GeneralController->basicsaveAction()\n#2 /var/www/html/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('basicsave')\n#3 /var/www/html/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))\n#4 /var/www/html/magento/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()\n#5 /var/www/html/magento/app in /var/www/html/magento/lib/Varien/Object.php on line 243, referer: http://magento.localhost/property/property/form

**Comment by sathishkumarContus** [comment]
Hi,

I noticed the data type is not recognised while saving the form, so that you are facing this problem. 
Please follow the below steps to overcome this problem.

**Step 1:** Go to the file path: app/code/local/Apptha/Airhotels/controllers/GeneralController.php 

**Step 2:**  Find **basicsaveAction**" function and Change the code 
     $product->addData (array($propertyData));  **instead of**   $product->addData ( $propertyData );

**Step 3:**  Also, Go to the file path: app/code/local/Apptha/Airhotels/Model/Status.php 

**Step 4:**  Find  "**saveFormData**" function. Add this code initial line of the function. 

Mage::app()->setCurrentStore(Mage::getModel('core/store')->load(Mage_Core_Model_App::ADMIN_STORE_ID)); 

Thanks,
Sathishkumar S
